# Generated by Django 4.2.7 on 2026-02-20 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAlgorithmRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('partial', 'Partiel (certains cours non assignés)')], default='running', max_length=20)),
                ('courses_total', models.PositiveIntegerField(default=0)),
                ('courses_assigned', models.PositiveIntegerField(default=0)),
                ('courses_unassigned', models.PositiveIntegerField(default=0)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('algorithm_log', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Exécution algorithme attribution',
                'verbose_name_plural': 'Exécutions algorithme attribution',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'Proposée (par algorithme)'), ('pending', 'En attente de confirmation'), ('confirmed', 'Confirmée'), ('declined', 'Refusée par le professeur'), ('cancelled', 'Annulée')], default='proposed', max_length=20)),
                ('assignment_method', models.CharField(choices=[('automatic', 'Attribution automatique (algorithme)'), ('manual', 'Attribution manuelle'), ('prof_request', 'Demande du professeur')], default='automatic', max_length=20)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0, verbose_name='Score de compatibilité (0-100)')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Attribution de cours',
                'verbose_name_plural': 'Attributions de cours',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='TeachingLoadReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('total_weekly_hours', models.PositiveIntegerField(default=0)),
                ('total_courses', models.PositiveIntegerField(default=0)),
                ('load_percentage', models.FloatField(default=0.0, verbose_name='% de la charge max')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('details', models.JSONField(default=dict)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
            ],
            options={
                'verbose_name': 'Rapport de charge',
                'verbose_name_plural': 'Rapports de charge',
                'ordering': ['-academic_year', 'semester', 'professor'],
            },
        ),
    ]
