# Generated by Django 4.2.7 on 2026-02-20 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_assignment', '0001_initial'),
        ('users', '0001_initial'),
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingloadreport',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_reports', to='users.professor'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic.course'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.professor'),
        ),
        migrations.AddField(
            model_name='assignmentalgorithmrun',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear'),
        ),
        migrations.AddField(
            model_name='assignmentalgorithmrun',
            name='run_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teachingloadreport',
            unique_together={('professor', 'academic_year', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('course', 'professor')},
        ),
    ]
