# Generated by Django 4.2.7 on 2026-02-20 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de vérification'), ('approved', 'Approuvée'), ('rejected', 'Rejetée (prérequis manquants)'), ('waived', 'Dispensée (dérogation accordée)')], default='pending', max_length=20)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('waiver_reason', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='academic.course')),
            ],
            options={
                'verbose_name': "Demande d'inscription",
                'verbose_name_plural': "Demandes d'inscription",
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='PrerequisiteCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('all_prerequisites_met', models.BooleanField(default=False)),
                ('missing_prerequisites', models.JSONField(default=list, verbose_name='Prérequis manquants')),
                ('met_prerequisites', models.JSONField(default=list, verbose_name='Prérequis satisfaits')),
                ('warnings', models.JSONField(default=list, verbose_name='Avertissements (recommandés non satisfaits)')),
                ('summary', models.TextField(blank=True)),
                ('enrollment_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_result', to='prerequisites.enrollmentrequest')),
            ],
            options={
                'verbose_name': 'Résultat vérification prérequis',
                'verbose_name_plural': 'Résultats vérifications prérequis',
            },
        ),
        migrations.CreateModel(
            name='ModulePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite_type', models.CharField(choices=[('strict', 'Strict (obligatoire, note ≥ 10/20)'), ('recommended', 'Recommandé (conseillé)'), ('coreq', 'Coréquisit (peut être suivi en parallèle)')], default='strict', max_length=20)),
                ('minimum_grade', models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Note minimale requise')),
                ('description', models.TextField(blank=True, verbose_name='Justification pédagogique')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='academic.module', verbose_name='Module cible')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='academic.module', verbose_name='Module prérequis')),
            ],
            options={
                'verbose_name': 'Prérequis de module',
                'verbose_name_plural': 'Prérequis de modules',
                'ordering': ['module', 'prerequisite_type'],
            },
        ),
    ]
