# Generated by Django 4.2.7 on 2026-02-20 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prerequisites', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleprerequisite',
            unique_together={('module', 'prerequisite')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentrequest',
            unique_together={('student', 'course')},
        ),
    ]
