# Generated by Django 4.2.7 on 2026-02-20 06:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('semester', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20)),
                ('week_start', models.DateField(verbose_name='Semaine de début')),
                ('week_end', models.DateField(verbose_name='Semaine de fin')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generation_log', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
                'ordering': ['-academic_year', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('room', 'Double réservation de salle'), ('professor', 'Double réservation professeur'), ('student', 'Chevauchement pour les étudiants'), ('capacity', 'Capacité salle dépassée')], max_length=30)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Conflit d'horaire",
                'verbose_name_plural': "Conflits d'horaires",
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')])),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='ex: Matin 1ère période')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Créneaux horaires',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_reference', models.CharField(max_length=10, verbose_name='Semaine (ex: 2024-W35)')),
                ('slot_type', models.CharField(choices=[('regular', 'Cours régulier'), ('makeup', 'Cours de rattrapage'), ('exam', 'Examen'), ('midterm', 'Partiel')], default='regular', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('rescheduled', 'Reporté')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='academic.course')),
            ],
            options={
                'verbose_name': 'Créneau planifié',
                'verbose_name_plural': 'Créneaux planifiés',
                'ordering': ['week_reference', 'time_slot__day_of_week', 'time_slot__start_time'],
            },
        ),
    ]
