# Generated by Django 4.2.7 on 2026-02-20 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('academic', '0002_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleslot',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='users.professor'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='academic.room'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='scheduling.timeslot'),
        ),
        migrations.AddField(
            model_name='scheduleconflict',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='scheduling.schedule'),
        ),
        migrations.AddField(
            model_name='scheduleconflict',
            name='slot_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_slot1', to='scheduling.scheduleslot'),
        ),
        migrations.AddField(
            model_name='scheduleconflict',
            name='slot_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_slot2', to='scheduling.scheduleslot'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academic.academicyear'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academic.level'),
        ),
    ]
